concatenate_feature_types : [1, 2, 3, 4, 5]
feature_lengths           : [69, 69, 15, 12, 56] 
concatenate_along_M       : False  # True: [B, n_feature*3, 1], False: [B, n_feature, 3]
partial_C                 : 25 # max 100
partial_sets              : 50 # max 100

batch_size                : 128
pin_memory                : True
num_workers               : 4
prefetch_factor           : 2