dataset:

# ========== parameter settings for the seqC ==========
  seqC_process: 'norm'
  nan2num: -1
  # seqC_process: 'summary'
  summary_type: 0
  # summary_type: 1  # 0: detailed information, 1: brief information

# # ========== parameter settings for the probR ==========
  num_max_sets                : 101 #101 in total
  num_max_theta_each_set      : 5000 #5000 in total
  
  one_dataset                 : True
  # num_train_sets              : [96] #96 in total
  num_train_sets              : [10] #101 in total
  # num_chosen_theta_each_set   : 500 #5000 in total
  num_chosen_theta_each_set   : 50 #5000 in total
  # validation_fraction         : 0.1
  validation_fraction         : [10, 20]
  # validation_num_theta        : 500
  validation_num_theta        : 50
  

  chosen_dur_trained_in_sequence: 
    - [3, 9, 15]
  crop_dur                    : True


  batch_process_method        : 'collate_fn'
  batch_size                  : 64
  # batch_process_method        : 'in_dataset'
  # batch_size                  : 1600
  num_probR_sample            : 50 #25
  shuffling_method            : 0 # 0: complex shuffling, 1: simple shuffling
  
  
  num_workers                 : 8
  pin_memory                  : True
  
  use_data_prefetcher         : True
  prefetch_factor             : 1