dataset:

# ========== parameter settings for the seqC ==========
  seqC_process: 'norm'
  nan2num: -1
  # seqC_process: 'summary'
  summary_type: 0
  # summary_type: 1  # 0: detailed information, 1: brief information

# # ========== parameter settings for the probR ==========
  num_chosen_sets             : [10, 20, 30, 40, 50] #101 in total
  num_chosen_theta_each_set   : 500 #5000 in total
  validation_fraction         : 0.1
  
  num_probR_sample            : 50 #25
  shuffling_method            : 0 # 0: complex shuffling, 1: simple shuffling

  batch_size                  : 50
  num_workers                 : 8
  chosen_dur_trained_in_sequence: 
    - [3, 5, 7, 9, 11, 13, 15]
    - [3, 5, 9, 13, 15]
    - [3, 5, 7, 9, 11, 13, 15]
    - [3, 9, 15]
    - [3, 5, 7, 9, 11, 13, 15]
  use_data_prefetcher         : True