# dataset:

# ========== parameter settings for the seqC ==========
seqC_process: 'norm'
nan2num: -1
# seqC_process: 'summary'
summary_type: 0
# summary_type: 1  # 0: detailed information, 1: brief information


# ========== parameter settings for the probR ==========
num_max_sets                : 20 #101 in total
num_max_theta_each_set      : 60 #5000 in total

chosen_dur_list             : [9, 11, 15]
crop_dur                    : True

permutation_mode            : 'online' # online, offline
num_probR_sample            : 20 #25


# ========== data loader settings ==========
batch_size                  : 5120 #=32*100
pin_memory                  : False
num_workers                 : 4
prefetch_factor             : 2
