concatenate_feature_types : [3]
feature_lengths           : [15]
concatenate_along_M       : True  # True: [B, n_feature*3, 1], False: [B, n_feature, 3]
partial_C                 : 10 # max 100
partial_sets              : 20 # max 100

batch_size                : 256 # 128
pin_memory                : True
num_workers               : 8
prefetch_factor           : 2