dataset:

# ========== parameter settings for the seqC ==========
  seqC_process: 'norm'
  nan2num: -1
  # seqC_process: 'summary'
  summary_type: 0
  # summary_type: 1  # 0: detailed information, 1: brief information

# # ========== parameter settings for the probR ==========
  num_probR_sample: 100
  
  num_theta_each_set: 1000