defaults:
  - _self_
  - experiment_settings: exp-set-0
  - prior: prior-0
  - x_o: x_o-0
  - simulator: model-0
  - dataset: dataset-p3
  - train: train-p3-0

pipeline_version: p3
log_dir: ./src/train/logs/train_L0/
data_path: /mnt/data/dataset/dataset_L0_exp_set_0.h5
seed: 100
debug: False
gpu: True
continue_from_checkpoint: ""