defaults:
  - _self_
  - experiment_settings: exp-set-test
  - prior: prior-test
  - x_o: x_o-0
  - simulator: model-0
  - dataset: dataset-p3-test
  - train: train-p3-0

pipeline_version: p3
log_dir: ./
data_path: /mnt/data/dataset/dataset_L0_exp_set_0.h5
seed: 100
debug: False
gpu: True
continue_from_checkpoint: ""