defaults:
  - _self_
  - experiment_settings: exp-set-0
  - prior: prior-3
  - x_o: x_o-0
  - simulator: model-0
  - dataset: dataset-p5-B
  - train: train-p5-conv_lstm-mdn

pipeline_version: p5a
log_dir: ./src/train/logs/train_L0_p5/p5a-conv_lstm-corr_conv-B
data_path: /home/wehe/data/NSC/data/dataset/dataset-L0-Eset0-100sets-T60-B20.h5
seed: 42
debug: True
gpu: True
continue_from_checkpoint: ""