train_data:
  save_name: 'train_data_Sa_Ra.h5'

# ========== parameter settings for the seqC ==========
  train_data_dur_list: [11]
  train_data_MS_list: [0.4]  # todo plot acc against MS

  subset_seqC: 0.15 # todo add option: when not value but a list, use the slicing/indexing
  subset_theta: 0.2 # todo same as above

  seqC_process: 'norm'
  nan2num: -1

  seqC_process: 'summary'
  summary_type: 1  # 0: detailed information, 1: brief information


# seqC_process: 'network'


# ========== parameter settings for the probR ==========
#  Rchoice_method: 'probR'

#  Rchoice_method: 'probR_sampling'
#  num_probR_sample: 10
#  num_probR_sample: 1

  Rchoice_method: 'probR_threshold'
  R_threshold: 0.5



# ========== parameter settings for the theta ==========
  remove_sigma2i: True