train_data:
  save_name: 'test_train_data.h5'

# ========== parameter settings for the seqC ==========
  train_data_dur_list: [11, 13]
  train_data_MS_list: [0.4, 0.8]  # todo plot acc against MS

#  subset_seqC: 0.15
#  subset_theta: 0.2

#  subset_seqC: [1]
#  subset_theta: 1

  subset_seqC: [0, 1]
  subset_theta: [0, 1, 2]

  seqC_process: 'norm'
  nan2num: -1

#  seqC_process: 'summary'
#  summary_type: 1  # 0: detailed information, 1: brief information
#  summary_type: 0


# seqC_process: 'network'


# ========== parameter settings for the probR ==========
  Rchoice_method: 'probR' # todo test

#  Rchoice_method: 'probR_sampling'
#  num_probR_sample: 10
#  num_probR_sample: 1

#  Rchoice_method: 'probR_threshold'
#  R_threshold: 0.5


# ========== parameter settings for the theta ==========
  remove_sigma2i: True