infer:
  method: 'snpe'
#  prior_min_train: [-3.7, 0, 0, -5]
#  prior_max_train: [2.5, 71, 18, 7]
  prior_min_train: [-2.5,   0,  0, -1]
  prior_max_train: [ 2.5,  30, 18,  1]
  prior_labels: ['bias', 'sigma2a', 'sigma2s', 'L0']

  num_atoms: 5
  training_batch_size: 50
  learning_rate: 5e-4
  validation_fraction: 0.1
  stop_after_epochs: 20
  max_num_epochs: 2147483647  # 2**31-1
  clip_max_norm: 5.0
  resume_training: False
  force_first_round_loss: False
  discard_prior_samples: False
  use_combined_loss: False
  retrain_from_scratch: False
  show_train_summary: True