train:
  inference:
    method: 'snpe'

  density_estimator:
    embedding_net: 
      type: lstm
      hidden_size: 64
      output_size: 32
    posterior_nn:
      model: maf
      hidden_features: 128
      num_transforms: 5
    

  training:
    
    max_num_epochs        : 2147483647
    max_num_dsets         : 2147483647

    print_freq            : 20 # 20 records per epoch
    learning_rate         : 1e-3

    improvement_threshold : 0.001 # improvement bigger than this threshold is considered as an improvement
    stop_after_epochs     : 12
    stop_after_dsets      : 5
    scheduler             : 'ReduceLROnPlateau'
    scheduler_params      : {'patience': 3, 'factor': 0.5, 'min_lr': 0}
    # stop_after_epochs     : 21
    # stop_after_dsets      : 5
    # scheduler             : 'CosineAnnealingWarmRestarts'
    # scheduler_params      : {'T_0': 7, 'T_mult': 2}
    
    clip_max_norm         : 4.0

    num_rounds            : 3
    num_runs              : 10
    num_atoms             : 10
    
  posterior:
    step          : 2     # the epoch steps to check posterior during training
    sampling_num  : 5000
    val_set_size  : 1