# prior:
num_prior_sample: 500
prior_min       : [-2.5,   0,  0,  -11]
prior_max       : [ 2.5,  77, 18,   10]
prior_labels    : ['bias', 'sigma2a', 'sigma2s', 'L0']
normalize       : False # true: normalize the prior to 0-1
ignore_ss       : False  # true: ignore the sigma2a sigma2s parameter
