tensorboard --logdir ./src/train/logs/train_L0/exp-d0-net0 --port 9000
tensorboard --logdir ./src/train/logs/train_L0/exp-d0-net1 --port 9001
tensorboard --logdir ./src/train/logs/train_L0/exp-d0-net2 --port 9002
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b0_2 --port 7010
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b0_3 --port 7001
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b0_3_ --port 7001
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b2_1 --port 7002
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b2_1_ --port 7003
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b2_2 --port 7004
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b2_2_ --port 7005
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b3_1 --port 7006
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b3_1_ --port 7007
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp_b3_2 --port 7008
/data/wehe/conda/envs/sbi/bin/tensorboard --logdir /home/wehe/scratch/train/logs/train_L0/exp-b2-1-contd0 --port 7009